apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-1
  template:
    metadata:
      labels:
        app: api-1
    spec:
      containers:
      - name: api-1
        image: sa/django:latest
        ports:
        - containerPort: 8800
        resources:
          limits:
            cpu: "2"
            memory: "2Gi"
        tty: true
        securityContext:
          runAsUser: 1000  # aiadm 사용자
---
apiVersion: v1
kind: Service
metadata:
  name: api-1-service
spec:
  selector:
    app: api-1
  ports:
  - protocol: TCP
    port: 8800
    targetPort: 8800
    nodePort: 30801
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-2
  template:
    metadata:
      labels:
        app: api-2
    spec:
      containers:
      - name: api-2
        image: sa/django:latest
        ports:
        - containerPort: 8800
        resources:
          limits:
            cpu: "2"
            memory: "2Gi"
        tty: true
        securityContext:
          runAsUser: 1000  # aiadm 사용자
---
apiVersion: v1
kind: Service
metadata:
  name: api-2-service
spec:
  selector:
    app: api-2
  ports:
  - protocol: TCP
    port: 8800
    targetPort: 8800
    nodePort: 30802
  type: NodePort
